=== walt-id/waltid-ssikit-vclib/src/test/resources/schemas/LegalPerson.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "gx-participant:blockchainAccountId" : {
          "type" : "string"
        },
        "gx-participant:headquarterAddress" : {
          "type" : "object",
          "properties" : {
            "gx-participant:addressCode" : {
              "type" : "string"
            },
            "gx-participant:addressCountryCode" : {
              "type" : "string"
            },
            "gx-participant:postal-code" : {
              "type" : "string"
            },
            "gx-participant:street-address" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "gx-participant:legalAddress" : {
          "type" : "object",
          "properties" : {
            "gx-participant:addressCode" : {
              "type" : "string"
            },
            "gx-participant:addressCountryCode" : {
              "type" : "string"
            },
            "gx-participant:postal-code" : {
              "type" : "string"
            },
            "gx-participant:street-address" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "gx-participant:legalName" : {
          "type" : "string"
        },
        "gx-participant:registrationNumber" : {
          "type" : "object",
          "properties" : {
            "gx-participant:registrationNumberNumber" : {
              "type" : "string"
            },
            "gx-participant:registrationNumberType" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "gx-participant:termsAndConditions" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issued" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== walt-id/waltid-ssikit-vclib/src/test/resources/serialized/LegalPerson.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "credentialSubject": {
    "gx-participant:blockchainAccountId": "0x4C84a36fCDb7Bc750294A7f3B5ad5CA8F74C4A52",
    "gx-participant:headquarterAddress": {
      "gx-participant:addressCode": "DE-HH",
      "gx-participant:addressCountryCode": "DE",
      "gx-participant:postal-code": "22303",
      "gx-participant:street-address": "Geibelstraße 46b"
    },
    "gx-participant:legalAddress": {
      "gx-participant:addressCode": "DE-HH",
      "gx-participant:addressCountryCode": "DE",
      "gx-participant:postal-code": "22303",
      "gx-participant:street-address": "Geibelstraße 46b"
    },
    "gx-participant:legalName": "deltaDAO AG",
    "gx-participant:registrationNumber": {
      "gx-participant:registrationNumberNumber": "391200FJBNU0YW987L26",
      "gx-participant:registrationNumberType": "leiCode"
    },
    "gx-participant:termsAndConditions": "70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700",
    "id": "did:web:delta-dao.com"
  },
  "id": "https://delta-dao.com/.well-known/participant.json",
  "issuanceDate": "2022-09-15T20:05:20.997Z",
  "issuer": "did:web:delta-dao.com",
  "type": ["VerifiableCredential", "LegalPerson"]
}
